CREATE TABLE `amazon_sale_report` (
  `index` int NOT NULL,
  `order_id` varchar(45) NOT NULL,
  `order_date` date NOT NULL,
  `order_status` varchar(45) NOT NULL,
  `fulfilment` varchar(45) NOT NULL,
  `sales_channel` varchar(45) NOT NULL,
  `ship_service_level` varchar(45) NOT NULL,
  `style` varchar(45) NOT NULL,
  `sku` varchar(45) NOT NULL,
  `category` varchar(45) DEFAULT NULL,
  `product_size` varchar(45) DEFAULT NULL,
  `ASIN` varchar(45) DEFAULT NULL,
  `courier_status` varchar(45) DEFAULT NULL,
  `qty` int DEFAULT NULL,
  `currency` varchar(45) DEFAULT NULL,
  `amount` float DEFAULT NULL,
  `ship_city` varchar(500) DEFAULT NULL,
  `ship_state` varchar(500) DEFAULT NULL,
  `ship_postal` int DEFAULT NULL,
  `ship_count` varchar(45) DEFAULT NULL,
  `promotion_ids` text,
  `b2b` varchar(45) DEFAULT NULL,
  `fulfilled_by` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`index`,`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3